substitutions:
  friendly_name: Telnet Server

esphome:
  name: telnet-example

esp32:
  board: wemos_d1_mini32y
  
external_components:
  - source: github://RoboMagus/esphome-telnet-server
   
logger:
  level: VERBOSE # this will also show lines received on Serial in Log output

# See 
# https://esphome.io/components/logger.html#default-uart-gpio-pins
# for a breakdown of which microcontrollers use which pins
uart:
  - id: uart_0
    baud_rate: 115200
    tx_pin: GPIO1
    rx_pin: GPIO3
  - id: uart_2
    baud_rate: 9600
    tx_pin: GPIO17
    rx_pin: GPIO16

telnet_server:
  - id: standard
    port: 23
    uart_id: uart_0
  - id: aux
    port: 24
    uart_id: uart_2
