substitutions:
  friendly_name: Telnet Server

esphome:
  name: telnet-example

esp32:
  board: wemos_d1_mini32y
  
external_components:
  - source: github://RoboMagus/esphome-telnet-server
   
logger:
  level: VERBOSE # this will also show lines received on Serial in Log output

# Watch some other thing connected to the ESP32 instead of
# the normal serial console
uart:
  id: uart_2
  baud_rate: 9600
  tx_pin: GPIO17
  rx_pin: GPIO16
telnet_server:
  port: 23
  uart_id: uart_2
